# Generated by Django 4.2.5 on 2024-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("john", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="career",
            field=models.CharField(max_length=25),
        ),
    ]
