# Generated by Django 4.2.5 on 2024-05-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("john", "0002_alter_about_career"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="picture",
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_set",
                to="john.about",
            ),
        ),
    ]
